name: build test

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
        with:
          version: 11
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: install packages
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build

      - name: checksum
        run: |
          ACTUAL=$(find dist/ -type f -exec sha1sum {} + | sort | sha1sum | cut -d ' ' -f 1)
          echo "actual:   $ACTUAL"
          echo "expected: $EXPECTED_CHECKSUM"
          test "$ACTUAL" = "$EXPECTED_CHECKSUM"
        env:
          EXPECTED_CHECKSUM: "b10dc4b921c2e9e2e012948cf83a2e806a9e8ed9"
