name: build test

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: pnpm/action-setup@71c92474e7e4f5bca283fb17ef80fba9cdb2b4b1 # v6
        with:
          version: 10
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: install packages
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build

      - name: checksum
        run: |
          ACTUAL=$(find dist/ -type f -exec sha1sum {} + | sort | sha1sum | cut -d ' ' -f 1)
          echo "actual:   $ACTUAL"
          echo "expected: $EXPECTED_CHECKSUM"
          test "$ACTUAL" = "$EXPECTED_CHECKSUM"
        env:
          EXPECTED_CHECKSUM: "b10dc4b921c2e9e2e012948cf83a2e806a9e8ed9"
